---
title: "HW3_Text Mining"
author: "TYTso"
date: "2019/7/21"
output: html_document
---
#### 動機 : 分析文章中關鍵詞。

Source:https://technews.tw/2018/01/30/brains-and-machines/

#### 安裝套件
```{r}
library(readr)
library(magrittr)
library(jiebaR)
library(readxl)
library(dplyr)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
```

####匯入資料

```{r}
Sys.setlocale(category = "LC_ALL",locale = "cht")
bci=worker()
text<- "《駭客任務》及《阿凡達》電影中的科技已不再遙遠，隨著腦機介面（brain-computer interface，BCI）
科技的發展，人類透過意念來控制機器或外在裝置的目標已逐一實現。瑞士懷斯生物暨神經工程學中心
（Wyss Center for Bio and Neuroengineering）正在利用源於人體幹細胞的大腦組織進行研究，
裝載有大腦組織的細胞培養盤被放置在電極陣列之上，當電流通過時神經元（firing neurons）被觸發，
螢幕上開始出現高低起伏的波。
千萬別小看這些細微的神經元激活動作，因為所有智慧的產生，都是由這一個個細微的神經元活動累積而來，
當你正在閱讀這個句子時，你大腦中已有無數的神經元被激發， 辨識這些文字的型體，轉換為音素，
進而形成有意義的文字。

成年人大腦約有 850 億個神經元，而平均每個神經元又有一萬個對外連結至其他神經細胞，
試想要繪製出這樣錯綜複雜的神經網絡是多麼巨大的工程，然而一旦完成，關於大腦運作之謎將得以解開
，也就是說，利用 BCI 達到「意念控制外部裝置」的夢想就要成真了。

腦機介面的三大組成步驟為：

腦波訊號取得（signal acquisition）

神經元的動作電位（action potential）可透過侵入式（如直接安裝電極於腦內）和非侵入式方式
（如利用腦電波儀及近紅外線光譜儀）被記錄下來。

解碼（decoding）

利用機器學習（machine learning）的技術處理大腦訊號，透過模式辨識（pattern recognition）
產生控制訊號（control signal）。

應用（application）

控制訊號能夠啟動外部裝置的改變；腦機介面也可被用來刺激大腦。

BCI 這項科技最早應用在 2004 年，13 位癱瘓病患身上被植入了一項名為「BrainGate」的系統，
這項裝置是由一組小型電極所組成的陣列，稱作猶他電極陣列（Utah array），最初是由美國布朗大
學（Brown University）開發。

該裝置需植入大腦的運動皮質（motor cortex / 掌管身體運動），裝置上的電極能在有「想要移動手
」這個念頭時，偵測到放電的神經元，這些訊號能夠透過線路回流至腦部的解碼器，將這些訊息解碼
並轉譯為不同的行動輸出，如移動螢幕上的指標或控制四肢。

這項系統曾成功協助一位因中風而癱瘓的女士，使用機械手臂來完成喝咖啡的動作。也曾幫助癱瘓患
者以每分鐘 8 個字的速度完成打字，還曾被成功應用在失去功能的四肢。 2017 年，凱斯西儲大學
（Case Western Reserve University）的 Robert Kirsch 教授也在《Lancet》發表了一篇關於 BrainGate 
的研究，成功將裝置運用在一位因自行車事故癱瘓的患者雙手上，讓他在 8 年後首次憑藉自己的力量進食。

像這樣腦與機器的互動，以各種形式改變了許多人的生活。2014 年於巴西舉辦的世界盃足球開幕典
禮上，也呈現了用意念控制的機械外甲裝置來踢球，就像是電影《鋼鐵擂台》（ Real Steel）的迷
你版。另一項由德國圖賓根大學（University of Tübingen）Ujwal Chaudhary 主持的近期研究，
也利用一種功能性近紅外線光譜（fNIRS）科技，透過偵測腦部紅血球氧合變化，協助與 4 名閉鎖期的漸凍症患者溝通。
神經的活動能夠被刺激啟動也能夠被記錄下來。人工耳蝸裝置將聲音轉換為電子訊號並將它們傳至腦中，
腦深層電刺激（Deep Brain Stimulation）是以手術植入導線及脈衝產生器，藉此產生電流來幫助帕金森氏症的控制。

像這樣的技術也被用來治療其他動作失調疾病及精神疾病，NeuroPace 是一間位於矽谷的公司，
他們研發了一個可以監測癲癇發作時大腦的瞬間活動及訊號的系統，並即時產生電流刺激以制止癲癇發作。

在加州柏克萊大學的研究團隊分析了人在聆聽對話時的大腦顳葉（temporal lobe）的腦波活動，
歸納出一個人可以聽到什麼內容的預測模式，這項應用可能有助於開發語言處理裝置，
以協助失語症這類無法了解及表達語言的患者；同時，另一個柏克萊的研究團隊也透過腦部血球氧合變化來重建
受試者看過的影片內容，試想若能放大此應用，那麼讓盲者能夠透過視覺皮質的刺激來產生視覺影像將不再是夢想。

不過腦機介面有無限可能性，也有無限挑戰。目前一項先進的研究還在動物測試階段，為英國倫敦大學學院及 
Allen Institute 合作開發的「Neuropixel」微小矽探頭，被用在監測老鼠的腦部細胞層級活動；加州大學聖
地牙哥分校的研究團隊也成功開發出能夠預測斑胸草雀歌唱旋律的腦機介面。

加州理工大學（California Institute of Technology）則針對獼猴視覺皮質內細胞是如何解讀人的臉部特徵
進行研究，目前已能透過解碼腦部訊號產出高度準確的面容。然而，直接針對人體大腦的研究又更加的困難，
不僅是因為有法規限制，還因為人腦結構較其他物種大腦複雜。

即便是在實驗室中證實對人體有突破性發展的腦機介面，轉移到臨床應用的過程也相當艱辛。BrainGate 系統
2005 年在《Wired》雜誌首度被報導，早期 Cyberkinetics 公司曾嘗試將其商業化，透過 NeuroPace 公司在
法規上 20 餘年的推動及努力，終於在今年期待能有 500 名患者進行嘗試。

即便如此，還有許多臨床上的挑戰，目前 BCI 科技仍需要專家操作，BrainGate 主要研發的其中一位專家 
Leigh Hochberg 說，每一次線路穿過頭顱時都有感染的風險，植入物在腦內也不可避免會移動，移動時可能
會傷害到細胞，且大腦對於外來物體的免疫反應可能會啟動結痂反應，包覆電極導致失效。

此外，目前的植入物只能記錄一小部分大腦訊號。BrainGate 所使用的 Utah array 僅能捕捉數百個神經元
的放電，一項西北大學的研究指出，自 1950 年起，記錄神經元的數量每 7 年成長一倍，這與摩爾定
律（Moore’s Law）每兩年成長一倍的電腦運算力相比，相去甚遠。

而瑞士懷斯中心或許能夠讓侷限於實驗室的神經科技拓展到臨床層級。研究中心主持人 John Donoghue 提到，
目前最主要的挑戰包括經費上的資源，投資者往往因這項研究的時程漫長（意味資金回收時間漫長）、對艱深
技術的恐懼而卻步；另外這項科技需要許多跨領域的專才合作執行；然而最最重要的是這項科技的核心──有關
大腦如何運作的了解，目前才剛起步，未來還有很長一段路要走。
"
f<-table(bci[text])
g<-data.frame(f)
colnames(g) <- c("關鍵字","次數")
head(g)

w<-filter(data.frame(f),Freq > 5 )
head(w)
```

#### 繪圖
```{r}
wordcloud(w$Var1,w$Freq,random.order = F, ordered.colors = F,colors = rainbow(1000))
```



```{r}
ggplot(data.frame(w), aes(x =Var1, y =Freq,fill_time)) +
  geom_bar(stat = "identity") 

```

