---
title: "Avenger4"
author: "TYTso"
date: "2019/7/24"
output: html_document
---
**套件**
```{r}
library(rvest)
library(tidyverse)
```

## PTT-Movie版2019年復仇者聯盟4之討論熱度

###《復仇者聯盟：終局之戰》(註:復仇者聯盟4)是一部於2019年上映(註:台灣時間2019-04-24)的美國史詩超級英雄電影，改編自漫威漫畫旗下的超級英雄團隊復仇者聯盟，由漫威影業製作及華特迪士尼工作室電影發行
資料來源:https://zh.wikipedia.org/zh-tw/%E5%BE%A9%E4%BB%87%E8%80%85%E8%81%AF%E7%9B%9F%EF%BC%9A%E7%B5%82%E5%B1%80%E4%B9%8B%E6%88%B0

### Movie版搜尋關鍵字復4
```{r}
pttmoav4<-data.frame()

library(rvest)
for(id in 1:37)
{
  moav4 <- "https://www.ptt.cc/bbs/movie/search?page="
  url  <- paste0(moav4, as.character(id), "&q=復4" )
  
  postmoav4 <- read_html(url)
  post_title <- postmoav4%>% 
    html_nodes(".title a") %>%
    html_text()
  post_date <- postmoav4%>% 
    html_nodes(".date") %>%
    html_text()  
  
  pttmoav4 <- rbind(pttmoav4, data.frame(title= post_title,
                                                 date= post_date))
    pttmoav<-pttmoav4[-714:-731,]
 
}
```
### Movie版搜尋關鍵字復仇者聯盟4(2019年)
```{r}
pttmovieav4<-data.frame()

library(rvest)
for(id in 1:20)
{
  nbakawhi <- "https://www.ptt.cc/bbs/movie/search?page="
  url  <- paste0( nbakawhi, as.character(id), "&q=復仇者聯盟4" )
  
  movieav4 <- read_html(url)
  post_title <- movieav4%>% 
    html_nodes(".title a") %>%
    html_text()
  post_date <- movieav4%>% 
    html_nodes(".date") %>%
    html_text()  
  
  pttmovieav4 <- rbind(pttmovieav4, data.frame(title= post_title,
                                                 date= post_date))
  pttmovieav<-pttmovieav4[-397:-400,]
}
```

```{r}
pttmovieav<-pttmovieav4[-397:-400,]
library(dplyr)
library(lubridate)
avdata <- pttmoav %>% 
  mutate(date=as.character(date)) %>%
  mutate(month= month(as.POSIXlt(date, format="%m/%d")))
avmonc<-count(avdata,month)

avdata2 <- pttmovieav %>% 
  mutate(date=as.character(date)) %>%
  mutate(month= month(as.POSIXlt(date, format="%m/%d")))
avmonc2<-count(avdata2,month)

d<-merge(avmonc,avmonc2, by = "month", all = T)
d[is.na(d)] <- 0

posts<-c(d[1,2]+d[1,3],d[2,2]+d[2,3],d[3,2]+d[3,3],d[4,2]+d[4,3],d[5,2]+d[5,3],d[6,2]+d[6,3],d[7,2]+d[7,3])

month<-c(1,2,3,4,5,6,7)
totalposts<-data.frame(month,posts)
totalposts

```
```{r}
ggplot(totalposts,aes(x=month,y=posts))+
  geom_bar(stat = "identity")+ggtitle("復仇者聯盟4於2019年7月前之討論文章數")
```